# Generated by Django 5.2.15 on 2026-07-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('api_config', models.JSONField(blank=True, default=dict, verbose_name='Конфиг API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('honors_diploma_points', models.PositiveSmallIntegerField(default=10, verbose_name='Баллы за аттестат с отличием')),
                ('sync_interval_seconds', models.PositiveIntegerField(default=3600, verbose_name='Интервал синхронизации (сек)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Медицинский университет',
                'verbose_name_plural': 'Медицинские университеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('filter_params', models.JSONField(verbose_name='Параметры фильтрации')),
                ('min_fetch_score', models.PositiveSmallIntegerField(default=200, verbose_name='Порог остановки пагинации')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='universities.medicaluniversity', verbose_name='МУ')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['university__name', 'name'],
            },
        ),
    ]
