# Generated by Django 5.2.15 on 2026-07-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydirection',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='studydirection',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='universities.medicaluniversity', verbose_name='Медицинский университет'),
        ),
    ]
