# Generated by Django 5.2.15 on 2026-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_studydirection_seats_alter_studydirection_university'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='applied_universities',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='universities.medicaluniversity', verbose_name='Медицинский университет с поданными заявлениями'),
        ),
    ]
