# Generated by Django 5.2.15 on 2026-07-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('success', 'Успех'), ('error', 'Ошибка'), ('rate_limited', 'Rate limit')], default='pending', max_length=20, verbose_name='Статус')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Повтор после')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('records_fetched', models.PositiveIntegerField(default=0, verbose_name='Записей получено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_job', to='universities.studydirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Задача синхронизации',
                'verbose_name_plural': 'Задачи синхронизации',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abiturient_id', models.CharField(db_index=True, max_length=32, verbose_name='ID абитуриента')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('sstatus_ssp', models.CharField(max_length=255, verbose_name='Статус заявления')),
                ('nsummark', models.PositiveSmallIntegerField(verbose_name='Конкурсные баллы')),
                ('npriority_ssp', models.PositiveSmallIntegerField(verbose_name='Приоритет')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Дата получения')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='universities.studydirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Профиль абитуриента',
                'verbose_name_plural': 'Профили абитуриентов',
                'ordering': ['direction', 'position'],
                'constraints': [models.UniqueConstraint(fields=('direction', 'abiturient_id'), name='unique_profile_per_direction')],
            },
        ),
    ]
