# Generated by Django 5.2.15 on 2026-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='has_enrollment_consent',
            field=models.BooleanField(default=False, verbose_name='Есть согласие на зачисление'),
        ),
    ]
